import json
import os
from typing import Any

from mcp import ClientSession, StdioServerParameters
from langchain_core.tools import StructuredTool
from pydantic import create_model, Field


def _mcp_type_to_python(mcp_type: str, prop_schema: dict) -> type:
    """
    Map MCP types to Python types.
    Forces lists of primitive types .
    """
    if mcp_type == "array":
        items_schema = prop_schema.get("items", {})
        item_mcp_type = items_schema.get("type", "string")

        item_type = str
        if item_mcp_type in ("integer", "number"):
            item_type = int
        elif item_mcp_type == "boolean":
            item_type = bool
        elif item_mcp_type == "object":
            item_type = dict

        return list[item_type]

    if mcp_type in ("integer", "number"):
        return int
    elif mcp_type == "boolean":
        return bool
    elif mcp_type == "object":
        return dict

    return str


def convert_mcp_tools_to_langchain(
        mcp_tools: Any,
        session: ClientSession,
) -> list[StructuredTool]:
    """Convert MCP tool definitions into LangChain StructuredTools using precise typing definitions."""

    langchain_tools: list[StructuredTool] = []

    for tool in mcp_tools.tools:
        raw_schema = tool.inputSchema or {}
        properties: dict[str, Any] = raw_schema.get("properties", {})
        required: list[str] = raw_schema.get("required", [])

        field_definitions: dict[str, Any] = {}
        for prop_name, prop_schema in properties.items():
            mcp_type = prop_schema.get("type", "string")
            python_type = _mcp_type_to_python(mcp_type, prop_schema)
            description = prop_schema.get("description", "")

            if prop_name in required:
                field_definitions[prop_name] = (python_type, Field(description=description))
            else:
                field_definitions[prop_name] = (python_type | None, Field(default=None, description=description))

        args_schema = create_model(f"{tool.name}_args", **field_definitions)

        # Capture tool context for standard LangChain invocation loops
        def make_tool_fn(t_name: str, t_session: ClientSession):
            async def tool_fn(**kwargs: Any) -> str:
                # FIX: Remove any explicit None (null) arguments generated by Gemini
                # so the strict validation layer in the GitHub MCP server doesn't throw a type error.
                clean_kwargs = {k: v for k, v in kwargs.items() if v is not None}

                print(f"\n🔧 TOOL CALL: {t_name}")
                print("Args:", json.dumps(clean_kwargs, indent=2, default=str))

                result = await t_session.call_tool(t_name, clean_kwargs)
                output = str(
                    result.content if hasattr(result, "content") else result
                )

                print(
                    "📦 RESULT:",
                    output[:500] + "..." if len(output) > 500 else output,
                )
                return output

            return tool_fn

        langchain_tools.append(
            StructuredTool(
                name=tool.name,
                description=(tool.description or "")[:300],
                args_schema=args_schema,
                coroutine=make_tool_fn(tool.name, session),
            )
        )

    return langchain_tools


def github_server_params() -> StdioServerParameters:
    """Return MCP server parameters for the GitHub server with safe fallback PATH variables."""
    system_path = os.environ.get("PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")

    return StdioServerParameters(
        command="npx",
        args=["-y", "@modelcontextprotocol/server-github"],
        env={
            "GITHUB_PERSONAL_ACCESS_TOKEN": os.environ.get("GITHUB_PERSONAL_ACCESS_TOKEN", ""),
            "PATH": system_path,
        },
    )